name: Packer

on:

  push:
    branches: [main]

  workflow_dispatch:

jobs:
  packer-build:
    name: Packer Build
    runs-on: ubuntu-latest
    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
    steps:
          
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
 
      - run: mvn clean package -DskipTests

      - name: Install Packer
        run: sudo apt-get update && sudo apt-get install -y packer

      - name: Packer Build - Branches
        #if: github.event.pull_request.merged == true
        run: "packer build ./ami1.pkr.hcl"
