  name: Java CI with Maven and Packer

  on:
    push:
      branches: [main]
    pull_request:
      branches: [main]

    workflow_dispatch:

  jobs:
    build:

      runs-on: ubuntu-latest
      
      
      env:
      
        CI: true  
        ssh_username: "ec2-user"
        AWS_ACCESS_KEY_ID: AKIA2TWL72WVNGN2BN5R
        AWS_SECRET_ACCESS_KEY: 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

      steps:
      
      
   
        
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: sudo yum install -y jq
      

      - name: Install Packer
        run: sudo apt-get update && sudo apt-get install -y packer
      - name: Packer Init
        run: "packer init ./ami1.pkr.hcl"
      - name: Packer Build - Branches
        run: "packer validate ./ami1.pkr.hcl"

      - name: Packer Build - Branches
       # if: github.event.pull_request.merged == true
        run: "packer build ./ami1.pkr.hcl"
      - run: AMI_ID=$(jq -r '.builds[-1].artifact_id' ./manifest.json | cut -d ":" -f2)""
      - run: echo $AMI_ID
